# Based on https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/monitoring/service-monitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ printf "%s-%s" (include "rook-ceph-servicemonitor.fullname" .) "rook-ceph-mgr" | trunc 63 | trimSuffix "-" }}
  namespace: rook-ceph
  labels:
    team: rook
    {{ include "rook-ceph-servicemonitor.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - rook-ceph
  selector:
    matchLabels:
      app: rook-ceph-mgr
      rook_cluster: rook-ceph
  endpoints:
  - port: http-metrics
    path: /metrics
    interval: {{ .Values.rookMonitor.interval }}
    # Add the correct cluster labels so we know what cluster this comes from.
    relabelings:
    {{- toYaml .Values.rookMonitor.relabelings | nindent 6 }}
