{{- range $path, $content := .Files.Glob "files/*.yaml" }}
{{- $name := $path | base | trimSuffix ".yaml" }}

{{- if get $.Values.rules $name | default dict | pluck "enabled" $.Values.defaults | last }}

---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    {{- include "rules.labels" $ | nindent 4 }}
    {{- printf "%s.labels" $name | get $.Values.rules | default dict | mergeOverwrite dict $.Values.defaults.labels | toYaml | nindent 4 }}
  name: {{ printf "%s-%s" (include "rules.fullname" $) ($path | base | trimSuffix ".yaml") | trunc 63 }}
spec:
  {{- $content | toString | nindent 2 }}
{{- end }}
{{- end }}
